### ISSUE TITLE
suppressing double slashes

### ISSUE THREAD

**Issue by nsheff** [databio/folderfun#1]
In the vignette, in several places, `folderfun` outputs paths with double slashes. we should systematically address this so that it can handle folders that either do or do not include trailing slashes.

**Comment by nsheff** [comment]
@michalstolarczyk  -- double-slashes are showing up again on macos, can you take a look at this?

https://cran.r-project.org/web/checks/check_results_folderfun.html

CRAN says we need to address this before June 21 to stay on CRAN.

**Comment by nsheff** [comment]
@michal is this solved on macOS (so, I can re-release this to CRAN?)

**Comment by stolarczyk** [comment]
Yes, I’ve run the check and it worked after the fix
