### ISSUE TITLE
setff appends slash

### ISSUE THREAD

**Issue by vreuter** [databio/folderfun#5]
```
> setff("PROC.PROJ", "here")
Created folder function ffPROC.PROJ(): here/
> ffPROC.PROJ()
[1] "here/"

```

**Comment by stolarczyk** [comment]
yeah, it does that when no arguments to the newly created `ffPROC.PROJ()` are provided since the `file.path` is used to paste them to the result of the `ffPROC.PROJ()`. In this case `here` and `""`. I'll fix that, thanks.

**Comment by vreuter** [comment]
Cool, thanks!
