### ISSUE TITLE
Add lowercase option?

### ISSUE THREAD

**Issue by vreuter** [databio/folderfun#9]
I'm interested in the possibility of an option to `setff` to make the name of the returned function be lowercase. For example, I'd like to use `ffresources()` rather than `ffRESOURCES` after doing something like `setff("RESOURCES")`. Would others find this useful?

**Comment by stolarczyk** [comment]
That's a good idea, but I think it would need to return the original as well to avoid user's confusion. 
There's a [base R function](https://stat.ethz.ch/R-manual/R-devel/library/base/html/delayedAssign.html) that makes it possible to delay the evaluation of the expression that creates the object until it is needed. This might solve the issue of having both (?) 

And the new version should follow the `camelCaps` style, I guess.

**Comment by vreuter** [comment]
Well, I'd only want it to return both if the option were on by default. If the signature added something like a `lowercase` parameter that was opt-in rather than on by default, as a user I'd only expect the lowercase named function to be returned. Returning both would make for an odd-feeling return type since we'd need to do something like pack the results into a list. Even though in that scenario both would become available by virtue of the `assign`ments, as a package client it feels more stable to use a return type than rely on a side effect to an environment.

I'm basically equally fine with continuing to provide no such option at all and just continue using the all-caps version (in fact, that probably would make code that uses this package a bit more clear to read), but I wouldn't want addition of the option to complicate the return type. I suppose both could be `assign`ed and only the lowercase one `return`ed if that flag were on, but I also don't love the idea of extra bindings.

Regarding the naming, are you saying that it should be `ffResources`? In general, I love the consistency that we have from adhering to that convention and for compliance with Bioconductor style, but I think we should apply that only in static code. For created and named programmatically, we shouldn't need to adhere to that (and don't, since we return things like `ffRESOURCES`). As a user, I'd be confused if I requested something like `nameLowerCase` to control the name and got back something called `ffResources`. I may've not understood what you were saying re: naming, though? If so, sorry about the confusion.

**Comment by stolarczyk** [comment]
Yeah, you're right about the multiple return situation.

But, thinking about it more, your goal can be also achieved simply by running:

```r
setff(name="resources", currVar="RESOURCES")
```
Did I understand it correctly? 

Maybe we just document it in the vignette that's enough?

**Comment by nsheff** [comment]
Or, why wouldn't you just use `setff("resources")` if you wanted it in lowercase?

**Comment by vreuter** [comment]
> But, thinking about it more, your goal can be also achieved simply by running:
> 
> ```r
> setff(name="resources", currVar="RESOURCES")
> ```
> 
> Did I understand it correctly?
> 
> Maybe we just document it in the vignette that's enough?

Yep, that'd do it. I mainly want this for the convenience of the frequent (at least for me) usage pattern like you showed @michalstolarczyk -- i.e., your example would become just `setff("RESOURCES")` if this were implemented. Pretty minor, but I'd use this a lot.

@nsheff I think the check is case-sensitive, right? So I'd need to have `resources` set rather than `RESOURCES` for the inference to work as I'm proposing here. Or did you mean including the `currVar` as @michalstolarczyk  suggested?

**Comment by nsheff** [comment]
I don't understand how this is relevant, really... I am not familiar with `currVar`.

Wouldn't you just use `setff(name="resources", location="/path/to/resources")` ?

I think there is a disconnect here with communication as to what `setff` does.

Is `RESOURCES` an environment variable? in that case you would say:

```
setff("resources", Sys.getenv("RESOURCES"))
```

right?

What is `currVar` ?

**Comment by vreuter** [comment]
> ```
> setff("resources", Sys.getenv("RESOURCES"))
> ```
> 
> right?
> 
> What is `currVar` ?

It's for specifying the name from which to pull the value to pass to `location` (called `path` on `dev`). Rather than restricting to env. var., it first favors `options` then checks for an env var.

**Comment by nsheff** [comment]
> It's for specifying the name from which to pull the value to pass to location (called path on dev). Rather than restricting to env. var., it first favors options then checks for an env var.

Got it. So it takes over the original task of `inff`.

**Comment by vreuter** [comment]
Yep, exactly. I really like that sort of priority search protocol and wanted to keep it

**Comment by nsheff** [comment]
> I'm interested in the possibility of an option to setff to make the name of the returned function be lowercase. For example, I'd like to use ffresources() rather than ffRESOURCES after doing something like setff("RESOURCES"). Would others find this useful?

What about making it so that the value passed to `setff` is *always* the verbatim function that is created, but it could also look in case-insensitive places? in this case your use would be:

```
setff("resources")
```

It could look in `RESOURCES` if it can't find something in `resources`. I find this easier to read than the original proposal.

**Comment by nsheff** [comment]
It also maintains:

- the code you write is exactly what you get, which makes it easier to read
- the function already tries to be smart by looking first in R options, then in environment variables. this just continues that.

**Comment by nsheff** [comment]
Personally I would use it like:

`setff("Resources")` since I'd want my function to be `ffResources()` -- but it could look first in `$Resources`, then in `$RESOURCES`, then in `$resources` -- first in options, then repeat in env variables. So there are  6 possibilities in that priority order.

**Comment by vreuter** [comment]
Agree on all counts. I like the aspect of lack of behavioral surprise to the user, and love the flexible search and greater user empowerment. This will also be nicer in terms of still being able to name env vars in all caps while not needing to type in all caps to get the desired lookup. :+1:  for not needing to type in all caps

**Comment by nsheff** [comment]
WHAT'S WRONG WITH ALL CAPS? IT'S SO EASY.
